import type { Metadata } from "next";

import "./globals.css";
import MainNavigation from "./components/MainNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <MainNavigation />
        {children}
      </body>
    </html>
  );
}
