import type { Metadata } from "next";

import "./globals.css";
import MainNavigation from "./components/MainNavigation";
import Footer from "./components/Footer";
import { Providers } from "./components/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased flex flex-col min-h-screen`}>
        {modal}
        <Providers>
          <MainNavigation />
          <div className="flex-1">{children}</div>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
